# Generated by Django 4.2.7 on 2023-12-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('resumen', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_post', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='post/default2.png', null=True, upload_to='post')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.categoria')),
            ],
            options={
                'ordering': ('-fecha_post',),
            },
        ),
    ]
