# Generated by Django 4.2.7 on 2023-12-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_resumen'),
        ('post', '0004_alter_categoria_nombre'),
    ]

    operations = [
    ]
