# Generated by Django 4.2.7 on 2023-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
