# Generated by Django 4.2.7 on 2023-12-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='activo',
        ),
    ]
