# Generated by Django 4.2.7 on 2023-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contador_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
