# Generated by Django 4.2.7 on 2023-12-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_contador_visitas'),
        ('post', '0015_alter_post_autor_alter_post_imagen'),
    ]

    operations = [
    ]
