# Generated by Django 4.2.7 on 2023-12-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_merge_20231217_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='post/default2.png', help_text='imagen 16:9 ó 370x140px', null=True, upload_to='post'),
        ),
    ]
