# Generated by Django 4.2.7 on 2023-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/default1.png', null=True, upload_to='usuarios'),
        ),
    ]
